### ISSUE TITLE
error if not all instances initially mounted

### ISSUE THREAD

**Issue by SassNinja** [riot/hot-reload#11]
I'm using hot-reload in combination with [webpack-loader](https://github.com/riot/webpack-loader)

I've placed the same component multiple times on my page but I'm only mounting one of them (dependent on viewport)
When I make changes to the component's file I expect only the mounted component to be updated.

However it seems hot-reload tries to (re)mount all tags of that component on the page what causes the following error:
```
TypeError: Cannot read property 'unmount' of undefined
```

Some debugging showed me that `oldTag` is `undefined` when it's getting reloaded without being mounted before.
Therefore I'd suggest to simply check if oldTag isn't undefined before trying to unmount it
https://github.com/riot/hot-reload/blob/master/src/index.js#L19

@GianlucaGuarini what do you think?

**Comment by GianlucaGuarini** [comment]
Thank you for this bug. I will have a look at it. It should be trivial to solve it
