### ISSUE TITLE
riot.reload breaks the app

### ISSUE THREAD

**Issue by oussa** [riot/hot-reload#4]
With the following complete basic riot example: a counter with an increment and a decrement buttons.

Before adding the line `riot.reload('app')` a change to the file + a save would hot reload by losing the state (counter gets back to 0), now when trying to add `.reload` the whole interface no longer reacts.

Please check the example for more explanation.

### app.tag
```
<app>
  <div>
    <button onclick="{ increment }">Increment</button>
    <span>{ count }</span>
    <button onclick="{ decrement }">Decrement</button>
  </div>
  <script>
    this.on('before-mount', () => {
      this.count = 0;
    });

    this.increment = () => {
      this.count += 1;
      console.debug('incr', this.count);
    };

    this.decrement = () => {
      this.count -= 1;
      console.debug('decr', this.count);
    };
  </script>
```

### index.js
```
import riot from 'riot';
import 'riot-hot-reload';

import '../components/app.tag';

riot.mount('app');
console.warn('mounted');

if (module.hot) {
  module.hot.accept('../components/app.tag', () => {
    console.warn('hot reloaded');

    riot.mount('app'); // current thing, works but kills the context

    // riot.reload('app'); // as soon as I use this instead, the UI doesn't get updated anymore,
    // the count stays visually at its last value even though in the console.log it show the real value,
    // `reload` instead of doing what it should, it's just breaking the UI
  });
}
```

## Versions
- "riot": "^3.8.1",
- "riot-tag-loader": "^2.0.2",
- "riot-hot-reload": "^1.0.0",
- "webpack": "^3.10.0",
- "webpack-dev-middleware": "^2.0.2",
- "webpack-hot-middleware": "^2.21.0",

**Comment by GianlucaGuarini** [comment]
the `before-mount` event will be always called when a component will be remounted. Avoid resetting your components properties via riot lifecycle events and everything will be fine
