### ISSUE TITLE
[BUG] Component CSS not updated when using hot reload

### ISSUE THREAD

**Issue by luffs** [riot/hot-reload#6]
1. Describe your issue:

Modified CSS doesn't get updated when component re-added, ex. via hot reload.
HTML and JS is updated properly.

2. Can you reproduce the issue? Yes, but it should be pretty obvious.

3. On which browser/OS does the issue appear? All.

4. Which version of Riot does it affect? 4.0.0-rc.6

I've created a pull request https://github.com/riot/riot/pull/2677

**Comment by GianlucaGuarini** [comment]
Fixed in @riotjs/hot-reload-4.0.0-rc.1
